name: IaC (container)

on:
  - workflow_dispatch 

env:
  RG_LA: 'jmfzga-container-la-uat'
  RG_CON: 'jmfzga-container-con-uat'
  IMAGE_NAME: 'jmfzga-image-name'
  IMAGE_TAG: 'jmfzga-image-tag'

jobs:
  deploy-all: 
    runs-on: ubuntu-latest
    steps:
                      
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS  }}
        enable-AzPSSession: true 

    - name: Checkout
      uses: actions/checkout@v1

    - name: Deploy Container Resources
      uses: Azure/arm-deploy@v1.0.1
      id: acrdeploy
      with:
        scope: resourcegroup  
        subscriptionId: ${{ secrets.AZURE_SUB }}
        resourceGroupName:  ${{ env.RG_LA }}
        template: ARM/acr-template.json
        parameters: ARM/acr-parameters.json
        deploymentMode: Incremental
   
    - name: Deploy Connector Resources 
      id: condeploy
      uses: Azure/arm-deploy@v1.0.1
      with:
        scope: resourcegroup  
        subscriptionId: ${{ secrets.AZURE_SUB }}
        resourceGroupName: ${{ env.RG_CON }}
        template: ARM/connectors-template.json
        parameters: ARM/connectors-parameters.json logicAppSystemAssignedIdentityTenantId=${{ steps.acrdeploy.outputs.logicAppSystemAssignedIdentityTenantId }} logicAppSystemAssignedIdentityObjectId=${{ steps.acrdeploy.outputs.logicAppSystemAssignedIdentityObjectId }}
        deploymentMode: Incremental

    - name: Generate Connections
      uses: azure/powershell@v1
      with:
        inlineScript: |
          ./Scripts/Generate-Connections.ps1 -resourceGroup '${{ env.RG_CON }}'
        azPSVersion: latest

    - name: 'Login to Azure Container Registry'
      uses: azure/docker-login@v1
      with:
        login-server: ${{ steps.acrdeploy.outputs.acrUsername }}.azurecr.io
        username: ${{ steps.acrdeploy.outputs.acrUsername }}
        password: ${{ steps.acrdeploy.outputs.acrPassword }}

    - name: 'Build & Push Docker Image'
      shell: bash
      run: |
        docker build . -t ${{ steps.acrdeploy.outputs.acrUsername }}.azurecr.io/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
        docker push ${{ steps.acrdeploy.outputs.acrUsername }}.azurecr.io/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}

    - name: 'Deploy Logic App Container'
      uses: Azure/functions-container-action@v1
      id: fa
      with:
        app-name: ${{ steps.acrdeploy.outputs.LAname }}
        image: '${{ steps.acrdeploy.outputs.acrUsername }}.azurecr.io/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}'
  